version: 2

models:
  - name: stg_token_transfers
    columns:
      - name: transaction_hash
        data_tests:
          - relationships:
              to: ref( 'stg_transactions')
              field: hash

  - name: stg_transactions_enriched
    description: Transactions in the Ethereum Blockchain
    columns:
      - name: value
        data_tests:
          - assert_value_amount_positive:
              field: block_number

  - name: stg_transactions
    description: Transactions in the Ethereum Blockchain
    columns:
      - name: hash
        description: >
          This is a very long multiline description about the unique
          identifier blah blah blah
        data_tests:
          - unique
          - not_null
          #- relationships:
          #    to: ref( 'stg_token_transfers')
          #    field: transaction_hash
          #    severity: warn
          #    config:
          #      store_failures: true
          #      store_failures_as: table
          #      where: date > current_date - 25
          
          
  - name: stablecoin_activity_per_day
    columns:
      - name: type
        data_type: varchar
        data_tests:
          - accepted_values:
              values: ['Hybrid','Crypto-backed','Fiat-backed']
              
unit_tests:
  - name: test_is_valid_transaction_category_breakdown
    model: stg_transactions_enriched
    overrides:
      macros:
        is_incremental: false
    given:
      - input: ref('stg_transactions')
        rows:
          - {receipt_contract_address: 'bla'}
      - input: ref('stg_token_transfers')
        rows:
          - {transaction_hash: 'bla'}
    expect:
      rows:
        - {transaction_category: 'contract_creation'}
